//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "generation", table_name = "histories")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub group: String,
    pub source: String,
    pub label: String,
    pub unit: String,
    #[sea_orm(column_type = "Float")]
    pub value: f32,
    pub remark: String,
    pub monitored_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::groups::Entity",
        from = "Column::Group",
        to = "super::groups::Column::Group",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Groups,
    #[sea_orm(
        belongs_to = "super::labels::Entity",
        from = "Column::Label",
        to = "super::labels::Column::Label",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Labels,
    #[sea_orm(
        belongs_to = "super::sources::Entity",
        from = "Column::Source",
        to = "super::sources::Column::Source",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Sources,
    #[sea_orm(
        belongs_to = "super::units::Entity",
        from = "Column::Unit",
        to = "super::units::Column::Unit",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Units,
}

impl Related<super::groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Groups.def()
    }
}

impl Related<super::labels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Labels.def()
    }
}

impl Related<super::sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sources.def()
    }
}

impl Related<super::units::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Units.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
