//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::groups::Entity as Groups;
pub use super::histories::Entity as Histories;
pub use super::labels::Entity as Labels;
pub use super::sources::Entity as Sources;
pub use super::units::Entity as Units;
